image:
  repository: thedevopsdude/python-app
  tag: 26c7d4d
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

serviceAccount:
  create: false

autoscaling:
  enabled: false

ingress:
  enabled: false
