image:
  repository: thedevopsdude/python-app
  tag: 9500e21
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: python-app.local
      paths:
        - path: /
          pathType: Prefix

serviceAccount:
  create: false

autoscaling:
  enabled: false
