---
name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Short SHA
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      - name: Update Helm dependencies
        run: helm dependency update ./python-app

      - name: Build Docker image
        run: |
          docker build -t thedevopsdude/python-app:${{ env.SHORT_SHA }} .

      - name: Log in to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push thedevopsdude/python-app:${{ env.SHORT_SHA }}

      - name: Update Helm chart with new image tag
        run: |
          sed -i "s/tag:.*/tag: ${{ env.SHORT_SHA }}/" ./python-app/values.yaml
          git add ./python-app/values.yaml
          git commit -m "Updated image tag to ${{ env.SHORT_SHA }}"
          git push
